{% set name = "poetry-core" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry_core-{{ version }}.tar.gz
  sha256: f9dbbbd0ebf9755476a1d57f04b30e9aecf71ca9dc2fcd4b17aba92c0002aa04

build:
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - importlib-metadata >=1.7.0  # [py<38]

test:
  imports:
    - poetry.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-poetry/poetry-core
  summary: Poetry PEP 517 Build Backend
  description: Poetry PEP 517 Build Backend & Core Utilities
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/python-poetry/poetry-core
  doc_url: https://github.com/python-poetry/poetry-core/blob/{{ version }}/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar