{% set version = "1.0.0a9" %}

package:
  name: poetry-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry-core/poetry-core-{{ version }}.tar.gz
  sha256: f08e9829fd06609ca5615faa91739b589eb71e025a6aaf7ddffb698676eb7c8c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - intreehooks
  run:
    - python

test:
  imports:
    - poetry.core
    - poetry.core._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-core/
  summary: Core utilities for Poetry
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
