{% set name = "poetry-core" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b4033b71b99717a942030e074fec7e3082e5fde7a8ed10f02cd2413bdf940b1f

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

# Couldn't run the upstream tests due to dependency missing: poetry, tomli_w, build (for newer versions of python)
test:
  imports:
    - poetry.core
    - poetry.core._vendor
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-poetry/poetry-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Poetry PEP 517 Build Backend
  description: Poetry PEP 517 Build Backend & Core Utilities
  dev_url: https://github.com/python-poetry/poetry-core
  doc_url: https://github.com/python-poetry/poetry-core/blob/{{ version }}/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar