{% set name = "poetry-core" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 97e50d8593c8729d3f49364b428583e044087ee3def1e010c6496db76bd65ac5

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pendulum >=1.4.4
    - cachy >=0.2.0
    # cachy[msgpack]
    - msgpack-python

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - poetry.core
    - poetry.core._vendor
  requires:
    - pip
    - pytest
    - virtualenv
    - trove-classifiers
    - pytest-mock
    - python-build
    - tomli-w
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/python-poetry/poetry-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Poetry PEP 517 Build Backend
  description: Poetry PEP 517 Build Backend & Core Utilities
  dev_url: https://github.com/python-poetry/poetry-core
  doc_url: https://github.com/python-poetry/poetry-core/blob/{{ version }}/README.md

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
